config/routes.rb
Rails.application.routes.draw do

  match "/index" => "aaa_core#index", via: :get
  match "/events" => "aaa_core#events", via: :get
  match "/shop" => "aaa_core#shop", via: :get
  match "/discussion" => "aaa_core#discussion", via: :get

    root 'aaa_core#index'

end

app/controllers/aaa_core_controller.rb
class AaaCoreController < ApplicationController
  def index
    @title = 'Welcome'
  end

  def events
    @title = 'Events'
  end

  def shop
    @title = 'Shop'
  end

  def discussion
    @title = 'Discussion'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/aaa_core_helper.rb
module AaaCoreHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    # Return a title on a per-page basis.
def title
    base_title = "Ashtead Allotments Association"
    if @title.nil?
    base_title
    else
    "#{base_title} | #{@title}"
    end
end
end

app/views/aaa_core/discussion.html.erb
<h1>AaaCore#discussion</h1>
<p>Find me in app/views/aaa_core/discussion.html.erb</p>

app/views/aaa_core/events.html.erb
<h1>AaaCore#events</h1>
<p>Find me in app/views/aaa_core/events.html.erb</p>

app/views/aaa_core/index.html.erb
<h1>Welcome</h1>
<p>Here is the welcome text</p></p>

app/views/aaa_core/shop.html.erb
<h1>AaaCore#shop</h1>
<p>Find me in app/views/aaa_core/shop.html.erb</p>

app/views/layouts/_footer.html.erb
<footer>
Copyright <%= Time.now.year %> Ashtead Allotments Association    
</footer>

app/views/layouts/_header.html.erb
<header>
<h1>Ashtead Allotments Association</h1>
<h2>Healthy Eating and Exercise preserve Life's Balance</h2>
</header>

app/views/layouts/_navigation.html.erb
<nav>
<ul>
<li><%= link_to "Home", root_path %></li>
<li><%= link_to "Events", events_path %></li>
<li><%= link_to "Discussion", discussion_path %></li>
<li><%= link_to "Shop", shop_path %></li>
</ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<%= render 'layouts/navigation' %>
<%= yield %>
<%= render 'layouts/footer' %>

</body>
</html>